name: pdf_reader
description: "A new Flutter project for Manga / PDF Reader with 3D Page Flip."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icon
  cupertino_icons: ^1.0.6

  # Networking & PDF processing
  http: ^1.2.0
  pdfx: ^2.6.0

  # 3D Page Flip effect
  page_flip: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
